CREATE TABLE "mot_interdit" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "mot_interdit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mot" text NOT NULL,
	"entier" boolean DEFAULT false NOT NULL,
	"cree_le" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mot_interdit_mot_unique" UNIQUE("mot"),
	CONSTRAINT "mot_interdit_a_plat" CHECK ("mot_interdit"."mot" ~ '^[a-z0-9]+$')
);
--> statement-breakpoint
-- La liste de départ (US-0138) : injures, termes sexuels et haineux courants, en français et en
-- anglais, et les noms de l'équipe du jeu. Elle se complète ensuite directement en base.
INSERT INTO "mot_interdit" ("mot", "entier") VALUES
  ('connard', false),
  ('connasse', false),
  ('salope', false),
  ('salaud', false),
  ('encule', false),
  ('batard', false),
  ('enfoire', false),
  ('gouine', false),
  ('merde', false),
  ('putain', false),
  ('couille', false),
  ('negre', false),
  ('nigger', false),
  ('nigga', false),
  ('faggot', false),
  ('pedophile', false),
  ('zoophile', false),
  ('hitler', false),
  ('jihad', false),
  ('daech', false),
  ('terroriste', false),
  ('violeur', false),
  ('inceste', false),
  ('porno', false),
  ('penis', false),
  ('vagin', false),
  ('sexe', false),
  ('fuck', false),
  ('bitch', false),
  ('whore', false),
  ('slut', false),
  ('pussy', false),
  ('kkk', false),
  ('bestia', false),
  ('administrateur', false),
  ('moderateur', false),
  ('moderatrice', false),
  ('con', true),
  ('cons', true),
  ('conne', true),
  ('connes', true),
  ('cul', true),
  ('pute', true),
  ('putes', true),
  ('pd', true),
  ('pede', true),
  ('pedes', true),
  ('tapette', true),
  ('bite', true),
  ('bites', true),
  ('chatte', true),
  ('zizi', true),
  ('nique', true),
  ('niquer', true),
  ('fdp', true),
  ('ntm', true),
  ('tg', true),
  ('shit', true),
  ('cunt', true),
  ('dick', true),
  ('cock', true),
  ('fag', true),
  ('retard', true),
  ('heil', true),
  ('nazi', true),
  ('nazis', true),
  ('pedo', true),
  ('viol', true),
  ('chienne', true),
  ('porn', true),
  ('admin', true),
  ('modo', true),
  ('support', true),
  ('staff', true),
  ('officiel', true),
  ('equipe', true)
ON CONFLICT ("mot") DO NOTHING;
